
project_id = "cskzzmsmelleemoafuhs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

# Explicitly set verify_jwt to true for the semrush-keywords function
[functions.semrush-keywords]
verify_jwt = true
