project_id = "qkqjdzzsgplmdqtkyrrc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.semrush-keywords]
verify_jwt = false

[functions.manage-integrations]
verify_jwt = false

[functions.update-admin-domain]
verify_jwt = false

[functions.update-admin-function]
verify_jwt = false

[functions.content-embeddings]
verify_jwt = false

[functions.rag-content-search]
verify_jwt = false

[functions.enhanced-content-generation]
verify_jwt = false