
project_id = "cskzzmsmelleemoafuhs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

# Make the semrush-keywords function verify JWT but handle errors gracefully
[functions.semrush-keywords]
verify_jwt = false
