// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkqjdzzsgplmdqtkyrrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcWpkenpzZ3BsbWRxdGt5cnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjA1MDgsImV4cCI6MjA2NjI5NjUwOH0.V2MAsvUsAaxMOS6juAdddU6HR8WIDKbSd2-roJnaxzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);