// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cskzzmsmelleemoafuhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNza3p6bXNtZWxsZWVtb2FmdWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjc0NjYsImV4cCI6MjA2MDQwMzQ2Nn0.yhgvc7TsdPB9brF5ngQSxBOLF81YTCxLWqQ6XN4Z4SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);